spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dvdrental
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    # open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        # default_batch_fetch_size: 1000

logging.level:
  org.hibernate.SQL: debug
